version: '3.4'
services:
  BDMS-server-all:
    container_name: BDMS-server-all
    image: ghcr.io/yvesyc/BDMS-server-all:v1.8.1
    environment:
      TZ: Asia/Shanghai
    ports:
      # Web
      - "8686:8686" 
      # Login server
      - "8484:8484"
      # Channels.
      - "7575-7577:7575-7577"
    volumes:
      - ./BDMS-release:/opt/server
    command: 
      - --mybatis-flex.datasource.mysql.url=jdbc:mysql://BDMS-db:3306/BDMS?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
      - --mybatis-flex.datasource.mysql.username=root
      - --mybatis-flex.datasource.mysql.password=root
      - --gms.service.wan-host=127.0.0.1
      - --gms.service.lan-host=127.0.0.1
      - --gms.service.localhost=127.0.0.1
    # healthcheck:
    #   test: ["CMD", "wget", "--spider", "http://localhost:8686/"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 10
    depends_on:
      BDMS-db:
        condition: service_healthy
    networks:
      - BDMS-network

  BDMS-db:
    container_name: BDMS-db
    image: mysql:8.4.0
    environment:
      # mysql root 默认密码
      MYSQL_ROOT_PASSWORD: "root" 
    ports:
      - "3306:3306"
    volumes:
      - ./docker-db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - BDMS-network

networks:
  BDMS-network:
    driver: bridge
